name: foody_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.6.8
  email_validator: ^3.0.0
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_awesome_buttons: ^1.1.0
  flutter_cache_manager: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.2.1
  flutter_stripe: ^11.5.0
  geocoding: ^4.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.3.0
  http: ^0.13.6
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  permission_handler: ^12.0.0+1
  search_map_place_updated: ^0.0.4
  shimmer_animation: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Ubuntu
    fonts:
    - asset: fonts/Ubuntu/Ubuntu-Light.ttf
  - family: Ubuntu-bold
    fonts:
    - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
  assets:
    - images/
